---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/services/ansible_openvpn/docker/semaphore"
    schedule:
      interval: "weekly"
