language: c
sudo: false
python:
  - "2.7"

install:
  pip install -q numpy cython
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make all
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - cd ..
  - python setup.py test
