- name: Fetch RPI list from OpenVPN
  ansible.builtin.import_playbook: fetch_openvpn_hosts.yml
- name: Fetch RPI status information
  hosts: rpi
  gather_facts: no
  connection: ssh
  tasks:
    - name: Fetch hostname and eth0 mac
      ansible.builtin.shell: |
        cat /etc/hosts | grep 127.0.1.1 | awk '{print $2}'
        /usr/sbin/ifconfig eth0 2>/dev/null|awk '/ether/ {print $2}'
      register: rpi_host
    - name: Launch python script for pijuice stats
      ansible.builtin.script:
        cmd: pijuice/pijuice_getbattery_voltage.py
      args:
        executable: python3
      register: result
    - name: Print result
      ansible.builtin.debug:
        msg: Raspberry Pi {{rpi_host.stdout}}
