# To execute each 15 minutes
# 0/15 * * * *
- hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: Fetch and process
        
- name: Fetch RPI list
  ansible.builtin.import_playbook: fetch_openvpn_hosts.yml

# Too old ansible version currently to use this
#- name: Refresh inventory to ensure new instances exist in inventory
#  ansible.builtin.meta: refresh_inventory
  
- name: Fetch RPI data using rsync
  ansible.builtin.import_playbook: fetch_rpi_data.yml

- name: Parse json and push to elastic search instance
  ansible.builtin.import_playbook: parse_to_elasticsearch.yml
