- name: Execute python script to save host list file
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Launch python script from playbook
    ansible.builtin.script: openvpn_ansible.py
    args:
      executable: python3
    register: command_output
  - name: Print output to file
    ansible.builtin.copy:
      content: "{{command_output.stdout}}"
      dest: /home/semaphore/hosts.json
    delegate_to: localhost
  - name: Create your local file on master node
    ansible.builtin.file:
      path: /home/semaphore/hosts.json
      owner: semaphore
      group: 10001
      mode: '0644'
    delegate_to: localhost
