- name: synchronize module demo
  hosts: all
  become: false
  vars:
    source: '/home/pi/noisesensor/out/'
    destination: '/home/semaphore/data/'
  tasks:
  - name: rsync installed
    ansible.builtin.package:
      name: rsync
      state: present
    become: true
  - name: data synchronization
    ansible.posix.synchronize:
      mode: 'pull'
      src: '{{ source }}'
      dest: '{{ destination }}'
      rsync_opts:
        - "--remove-source-files"
        - "--exclude='*.tmp'"
