- name: Run vcgencmd measure_temp command on the remote host
  hosts: rpi
  gather_facts: no
  connection: ssh
  tasks:
    - name: Execute vcgencmd measure_temp
      ansible.builtin.command: vcgencmd measure_temp
      register: temp_output
    - name: fetch RPI eth0 mac address
      ansible.builtin.shell: /usr/sbin/ifconfig eth0 2>/dev/null|awk '/ether/ {print $2}'
      register: rpi_mac
    - name: Print temperature output
      ansible.builtin.debug:
        msg: Raspberry Pi {{ rpi_mac.stdout }} is {{temp_output.stdout}}
