- name: Reload ble agenda by restarting ble service
  hosts: rpi
  vars:
    ansible_remote_tmp: /run/user/1000
  tasks:
    - name: Restart noisesensor services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        daemon_reload: true
        enabled: true
        state: restarted
      with_items:
        - zeroble.service
