- name: Update noisesensor git repository and restart associated services
  hosts: rpi
  tasks:
    - name: Pull changes from noisesensor repository
      ansible.builtin.git:
        repo: https://github.com/Universite-Gustave-Eiffel/Rail4Earth.git
        dest: /home/pi/noisesensor/
        single_branch: yes
        version: main
      register: gitclone
    - name: Install services base python requirements
      ansible.builtin.pip:
        requirements: /home/pi/noisesensor/services/requirements.txt
      when: gitclone.changed
    - name: Install services ble python requirements
      ansible.builtin.pip:
        requirements: /home/pi/noisesensor/services/pixljs_alert/requirements.txt
      when: gitclone.changed
    - name: Restart noisesensor services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        daemon_reload: true
        enabled: true
        state: restarted
      with_items:
        - zeroble.service
        - zerogps.service
        - zeroindicators.service
        - zerorecord.service
        - zerostorage.service
        - zerostorage_indicators.service
        - zerotrigger.service
      when: gitclone.changed
