name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.11"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip' # caching pip dependencies
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Load cached tox
      uses: actions/cache@v2
      with:
        path: .tox
        key: tox-${{ matrix.platform }}-${{ matrix.python-version }}
    - name: Test
      run: python -m tox -e py